; HNS + LVL - Required AMXX Modules
; Autor: Bstr # Thynuviel
;
; Estos módulos son necesarios para el funcionamiento del sistema HNS + LVL

; Standard modules
; Fun
fun_amxx_i386.so
;fun_amxx_i386.dll
;fun_amxx_amd64.so

; CStrike
cstrike_amxx_i386.so
;cstrike_amxx_i386.dll
;cstrike_amxx_amd64.so

; CSX
csx_amxx_i386.so
;csx_amxx_i386.dll
;csx_amxx_amd64.so

; Required for HNS LVL
; SQLX (para SQLite)
sqlx_amxx_i386.so
;sqlx_amxx_i386.dll
;sqlx_amxx_amd64.so

; Fakemeta (para entidades y láseres)
fakemeta_amxx_i386.so
;fakemeta_amxx_i386.dll
;fakemeta_amxx_amd64.so

; HamSandwich (para hooks de eventos)
hamsandwich_amxx_i386.so
;hamsandwich_amxx_i386.dll
;hamsandwich_amxx_amd64.so

; Engine (opcional, para algunas funciones)
engine_amxx_i386.so
;engine_amxx_i386.dll
;engine_amxx_amd64.so