; Usuarios Premiums
; File location: $moddir/addons/amxmodx/configs/Premiums.ini

; S� la linea comienza con ';' o con '//' es un comentario (No se tiene en cuenta)

; Formato para crear un usuario premium correctamente:
; "Nombre EXACTO" "Multiplicacion de exp y puntos" "dd/mm/aaaa"

; Ejemplos de usuarios premiums:
; "Pepe" "4" "Nunca"

"Bstr # Thynuviel" "3" "Nunca"